### ISSUE TITLE
Homepage utility

### ISSUE THREAD

**Issue by thomasdavis** [cdnjs/static-website#17]
Hey guys, great work, much more consistent with some cool new UI tweaks. 

I'd just add that I think the homepage experience has become less easy to use. I'd wager that the growth of cdnjs over the years was from making the homepage super minimal and focussed on utility. 

The search bar is no longer the focus because the hero distracts from it and almost pushes the search bar below the fold on small laptops. (the search bar is also not autofoccused) 

When searching on the new beta the results are definitely after the fold. 

I've also personally always copied the url directly so displaying it in full I would personally prefer. 

And then when looking at an individual library, it's harder to get a feel for the contents of the library and the line wraps on the url's make it a harder to scan. 

I think you can drop Tutorials back below again because they aren't overly used. 

In essence it looks and feels more like a product than a developer utility.

Keep it up!

**Comment by MattIPv4** [comment]
> The search bar is no longer the focus because the hero distracts from it and almost pushes the search bar below the fold on small laptops. (the search bar is also not autofoccused)

Agreed, I think it makes sense to look at pulling it up as much as we can -- unsure about autofocusing though.

> I've also personally always copied the url directly so displaying it in full I would personally prefer.

I'm somewhat against doing this, as it encourages folks to use the resources without SRI -- we're trying to push folks wherever possible to start using SRI, so providing the copy button instead of just showing the URL here helps with that.

> And then when looking at an individual library, it's harder to get a feel for the contents of the library and the line wraps on the url's make it a harder to scan.
>
> I think you can drop Tutorials back below again because they aren't overly used.

Yeah, that makes sense, I agree with moving tutorials down. We can look at adding a CTA elsewhere above to go to the dedicated tutorials page if folks think we should.
