### ISSUE TITLE
Add "Copy Tag Without SRI"

### ISSUE THREAD

**Issue by zenull** [cdnjs/static-website#31]
### How the feature is useful

Not everyone needs SRI so Please Add/Leave "Copy Wittout SRI".
It's a must since a lot of people will be forced to remove SRI again and again. But for you is just a matter of 1 minute.
THX!!

**Comment by MattIPv4** [comment]
Using script/link tags without SRI is insecure and I'm not aware of any legitimate technical reason why you'd need to remove the SRI tag -- we believe that we should always be encouraging a more secure internet, which is why we are only providing the option to copy the script/link tags with SRI included.

If there is a legitimate technical reason for why you need to remove SRI, please say, but otherwise, I don't think we'll be adding back the non-SRI version of the copy button.

**Comment by xtuc** [comment]
Agree with @MattIPv4. It's quite the opposite: everyone needs SRI.
